// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tasky.DataAccess;

#nullable disable

namespace tasky.Migrations
{
    [DbContext(typeof(TaskyDBContext))]
    [Migration("20220825091830_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("tasky.Models.ProjectModel", b =>
                {
                    b.Property<int>("Id_Project")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("API")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("API_Framework")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DB")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DB_Management_Sys")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date_Finish")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date_Start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Finished")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Front")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Front_Framework")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ID_Languages")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.HasKey("Id_Project");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("tasky.Models.UserModel", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id_User");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
